#!/usr/bin/env python

# This file is part of Mesh.

# Mesh is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Mesh is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Mesh.  If not, see <http://www.gnu.org/licenses/>.

print """
Hi!  mesh is in alpha right now.  Once we reach beta, this file will do
something useful, like configure/launch mesh.  But not yet.

Here are some useful things you CAN do right now:

# Run core unit tests
test/run_test.py -v

# Run specific plugin unit tests
test/run_test.py -t p_someplugin

# Actually run a plugin in trial-run mode
src/master.py -t p_someplugin

# Try starting up this node for real
src/master.py

# Or read some of the documentation!
ls docs/
"""
